18praneeth/sushiksha-website

- templates/profile-detail.html
> Added a space before and after semicolon

- README.md
#25 I have updated the Readme.md.
> Minor updates to Readme.md file

- djangoProject/views.py
- static_in_env/assets/css/style.css
- templates/badge-create.html
- templates/leader.html
- templates/team.html
- templates/trainers.html
- users/models.py
- users/views.py
> Added name display in the list, corrected badge dropdown, badge appearance.

- templates/blog-single.html
- templates/head.html
Added Social media share buttons
> Share buttons position improvement

- blog/views.py
- templates/meta.html
Added a feature, now if we share a blog post it shows the overview and thumb line as a card in social media platform.
> Blog sharing supports card

- templates/profile-detail.html
- users/models.py
> Added house and team names when viewing detailed profile

- templates/header.html
Updated the team page so user name displays if a username if the user doesn't have a name.
> Changed the header

- static_in_env/assets/css/style.css
#18
1. Removed the highlight on input field
2. Increased the border size by 2px
> Made changes to the input field in users tab

- static_in_env/assets/css/style.css
3px border was too much and it was highlighting only search bar so I reduced it to 1px.
> Reduced the border for serach filed in memebers page

- blog/models.py
- blog/views.py
- static_in_env/assets/css/slider.css
- static_in_env/assets/css/style.css
- templates/blog-single.html
- templates/blog.html
#59 
1. Blog page title
2. Image compression when the user uploads the image as a thumbline to post.
3. Slider colour.
4. Updated Blog page title, now it dynamic for ex. A blog by XYX : TOPIC
> Added Image responsiveness, Blog page title, Image compression.

- static_in_env/assets/css/style.css
- templates/leader.html
- templates/login.html
- templates/trainers.html
- users/tests.py
- users/urls.py
- users/utils.py
- users/views.py
#74 , It has option to login with both the username and email id
#48
> Login with email id, separate tab for mentors and Mentee

- templates/rewards.html
- users/signals.py
- users/utils.py
- users/views.py
#95 
Thanks, @swasthikcnayak for working on this issue ❤️
> Categories for blogs

- templates/email/message.html
- templates/house.html
- users/signals.py
- users/utils.py
> Html mails and improved house dispaly

- templates/profile.html
#2 
Corrected Edit profile button
> Profile update button

- badge/filters.py
> Ordering of user

- templates/profile.html
- templates/search.html
- users/views.py
Created search functionality, added name-based search.
> New branch

- blog/models.py
- blog/views.py
- templates/header.html
- users/forms.py
- users/views.py
> added title to the blog-url referencing issue #21

- templates/house.html
- templates/profile.html
> team rendering corrected in leaderboard

- templates/house.html
- templates/leader.html
- templates/profile-detail.html
- templates/profile.html
- templates/team.html
- templates/trainers.html
- users/admin.py
- users/forms.py
- users/models.py
- users/views.py
> Stat downloads

- templates/profile-detail.html
- templates/profile.html
> Quick fix for profile page #188

- README.md
- requirements.txt
- templates/about.html
#191 added the line in Development
> added the line create /media folder in readme 

- users/admin.py
> Admin many to many field changes

- OKR/filters.py
- OKR/urls.py
- OKR/views.py
- templates/OKR/activity.html
- templates/include/header.html
- users/urls.py
> Okr activity

- templates/include/header.html
The header had an option called 'add an entry' that was misspelled.
> Minor error fixed

- templates/include/header.html
The additional OKR activity badge that was under the badge section has been removed
> Removed additional activity bar

- README.md
Added html tags and updated license on readme as per required standards.
> Updated license information

- templates/profile/profile-detail.html
- templates/profile/profile.html
> fix: user role
